// components/PostsList.vue
<template>
  <section>
    <ul>
      <li v-for="item in items" :key="item.slug" class="h-feed">
        <nuxt-link :to="item.path">
          <div class="meta">
            <h2 class="title p-name" v-text="item.title" />
            <time class="date dt-published" :datetime="item.createdAt">
              <a :href="fullPath" class="u-url">{{ item.createdAt | date }}</a>
            </time>
          </div>
          <div class="icon">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path d="M0 0h24v24H0V0z" fill="none" />
              <path
                d="M9.31 6.71c-.39.39-.39 1.02 0 1.41L13.19 12l-3.88 3.88c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0l4.59-4.59c.39-.39.39-1.02 0-1.41L10.72 6.7c-.38-.38-1.02-.38-1.41.01z"
              />
            </svg>
          </div>
        </nuxt-link>
      </li>
    </ul>
    <div class="update nuxt-content">
      <p>
        Check out the <a href="/posts/rss.xml">RSS feed</a> or
        <a href="https://twitter.com/luka_harambasic">my Twitter account</a>
        to keep up to date.
      </p>
    </div>
  </section>
</template>

<script>
export default {
  name: 'Items',
  props: {
    items: {
      type: Array,
      required: true,
    },
  },
  methods: {
    fullPath(path) {
      return `https://harambasic.de${path}`
    },
  },
}
</script>

<style lang="sass" scoped>
ul
  display: flex
  flex-direction: column
  flex-wrap: nowrap
  justify-content: flex-start
  align-content: space-between
  align-items: stretch
li
  > a
    display: flex
    flex-direction: row
    flex-wrap: nowrap
    justify-content: space-between
    align-content: flex-start
    align-items: center
    margin: 0 0 1rem 0
    text-decoration: none
    color: $color-primary
    transition: $animation
    border-radius: $border-radius
    padding: 1rem
    @media (prefers-color-scheme: dark)
      color: $color-light
      &:hover
        color: $color-primary
    @media screen and (max-width: $breakpoint-mobile)
      flex-direction: column
      justify-content: flex-start
      align-items: flex-start
    &:hover
      background: $color-secondary
      .icon
        background: $color-light
        svg
          fill: $color-primary
      .date
        a
          color: $color-primary
      @media (prefers-color-scheme: dark)
        .icon
          background: $color-primary
          svg
            fill: $color-secondary
    .icon
      display: flex
      flex-direction: row
      flex-wrap: nowrap
      justify-content: center
      align-content: center
      align-items: center
      background: $color-secondary
      border-radius: 50%
      font-size: 1.5rem
      line-height: 1.5rem
      padding: .5rem
      margin:  0 0 0 1rem
      transition: $animation
      @media screen and (max-width: $breakpoint-mobile)
        display: none
      svg
        fill: $color-primary
        width: 2rem
        height: 2rem
    .title
      font-size: 1.5rem
    .date
      font-size: 1rem
      @media screen and (max-width: $breakpoint-mobile)
        margin: .5rem 0 0 0
      a
        color: $color-primary
        text-decoration: none
        transition: $animation
        border-bottom: 2px solid transparent
        &:hover
          border-color: $color-primary
        @media (prefers-color-scheme: dark)
          color: $color-light
.update
  font-size: 1rem
  text-align: center
</style>

// src/components/posts/PostsList.svelte
<script lang="ts">
  import type { CollectionEntry } from 'astro:content'
  import Card from '@components/Card.svelte'
  import Categories from '@components/Categories.svelte'
  import Tags from '@components/Tags.svelte'
  import { urlStore } from '@util/urlStore.svelte'

  let { entries, categories, tags } = $props<{
    entries: CollectionEntry<'posts'>[]
    categories: CollectionEntry<'categories'>[]
    tags: CollectionEntry<'tags'>[]
  }>()

  const categoryParam = $derived(urlStore.searchParams.get('category'))
  const tagParam = $derived(urlStore.searchParams.get('tag'))

  let filteredEntries = $derived(
    entries.filter((entry) => {
      const hasCategory =
        categoryParam && entry.data.category.id === categoryParam
      const hasTag =
        tagParam && entry.data.tags.some((tag) => tag.id === tagParam)
      // If no params are set everythign should be in the list
      if (!categoryParam && !tagParam) return true
      // If both are set, it has to match both
      if (hasCategory && hasTag) return true
      if (!tagParam && hasCategory) return true
      if (!categoryParam && hasTag) return true
      return false
    })
  )

  function getEntriesCategories(id: string): CollectionEntry<'categories'>[] {
    return categories.filter(
      (category: CollectionEntry<'categories'>) => category.id === id
    )
  }

  function getEntriesTags(
    entryTagIds: { id: string }[]
  ): CollectionEntry<'tags'>[] {
    return tags.filter((tag: CollectionEntry<'tags'>) =>
      entryTagIds.find((entryTag) => tag.id === entryTag.id)
    )
  }
</script>

<section>
  <ul class="entries">
    {#if filteredEntries.length === 0 && (categoryParam || tagParam)}
      <Card>
        <p>
          No post was published with the selected category/tag. Try to remove
          one.
        </p>
      </Card>
    {:else}
      {#each filteredEntries as entry}
        <Card class="entry h-feed">
          <a href={`/posts/${entry.slug}`}>
            <div class="column">
              <Categories
                categories={getEntriesCategories(entry.data.category.id)}
              />
              <strong class="title">{entry.data.title}</strong>
            </div>
          </a>
          {#snippet left()}
            <Tags tags={getEntriesTags(entry.data.tags)} />
          {/snippet}
          {#snippet right()}
            <time class="dt-published" datetime={entry.data.published.raw}>
              {entry.data.published.formatted}
            </time>
          {/snippet}
        </Card>
      {/each}
    {/if}
  </ul>
  <aside>
    <Card direction="column">
      <h3>Categories</h3>
      <Categories {categories} />
    </Card>
    <Card direction="column">
      <h3>Tags</h3>
      <Tags {tags} />
    </Card>
  </aside>
</section>

<style lang="postcss">
  section {
    display: grid;
    grid-template-rows: auto auto auto;
    grid-template-columns: 70ch 1fr;
    column-gap: var(--l);
    row-gap: var(--l);
    width: 100%;
    @media screen and (max-width: 74rem) {
      grid-template-columns: 1fr 18rem;
    }
    @media screen and (max-width: 50rem) {
      grid-template-columns: 1fr;
    }
  }
  .entries {
    width: 100%;
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    align-content: stretch;
    justify-content: flex-start;
    align-items: stretch;
    gap: var(--l);
    @media screen and (max-width: 50rem) {
      grid-template-columns: 1fr;
      order: 1;
    }
  }
  :global(.entries .entry) {
    transition: var(--transition);
    &:hover {
      transform: scale(0.97);
      cursor: pointer;
      :global(svg) {
        opacity: 1;
      }
    }
    a {
      display: flex;
      position: relative;
      flex-direction: row;
      flex-wrap: nowrap;
      align-content: stretch;
      justify-content: space-between;
      align-items: flex-start;
      gap: var(--l);
      color: var(--c-font);
      text-decoration: none;
      @media screen and (max-width: 50rem) {
        flex-direction: column-reverse;
      }
      .column {
        display: flex;
        flex-direction: column;
        flex-wrap: nowrap;
        align-content: stretch;
        justify-content: flex-start;
        align-items: stretch;
        gap: var(--xs);
      }
      .title {
        display: inline-block;
        font-weight: 900;
        font-size: var(--font-m);
        line-height: 1.2;
        font-family: var(--font-family);
        letter-spacing: var(--font-letter-spacing-headline);
      }
      :global(.arrow) {
        color: var(--c-font-accent-dark);
        size: var(--l);
        position: absolute;
        top: var(--m);
        right: calc((-1) * var(--m));
        opacity: 0;
        transition: var(--transition);
        border: 4px solid var(--c-light);
        border-radius: 100%;
        background: var(--c-light);
        box-shadow:
          0 1px 2px rgba(0, 0, 0, 0.03),
          0 2px 4px rgba(0, 0, 0, 0.03),
          0 4px 8px rgba(0, 0, 0, 0.03),
          0 8px 16px rgba(0, 0, 0, 0.03),
          0 16px 32px rgba(0, 0, 0, 0.03),
          0 32px 64px rgba(0, 0, 0, 0.03);
      }
    }
  }
  aside {
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    align-content: stretch;
    justify-content: flex-start;
    align-items: stretch;
    gap: var(--l);
    width: 100%;
    @media screen and (max-width: 50rem) {
      grid-template-columns: 1fr;
      order: 0;
    }
    h3 {
      display: inline-block;
      font-weight: 900;
      font-size: var(--font-m);
      line-height: 1;
      font-family: var(--font-family);
      letter-spacing: var(--font-letter-spacing-headline);
    }
    .tags {
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      gap: var(--xs);
      align-items: flex-start;
      justify-content: flex-start;
    }
  }
</style>
