// components/PostsList.vue
<template>
  <section>
    <ul>
      <li v-for="item in items" :key="item.slug" class="h-feed">
        <nuxt-link :to="item.path">
          <div class="meta">
            <h2 class="title p-name" v-text="item.title" />
            <time class="date dt-published" :datetime="item.createdAt">
              <a :href="fullPath" class="u-url">{{ item.createdAt | date }}</a>
            </time>
          </div>
          <div class="icon">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path d="M0 0h24v24H0V0z" fill="none" />
              <path
                d="M9.31 6.71c-.39.39-.39 1.02 0 1.41L13.19 12l-3.88 3.88c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0l4.59-4.59c.39-.39.39-1.02 0-1.41L10.72 6.7c-.38-.38-1.02-.38-1.41.01z"
              />
            </svg>
          </div>
        </nuxt-link>
      </li>
    </ul>
    <div class="update nuxt-content">
      <p>
        Check out the <a href="/posts/rss.xml">RSS feed</a> or
        <a href="https://twitter.com/luka_harambasic">my Twitter account</a>
        to keep up to date.
      </p>
    </div>
  </section>
</template>

<script>
export default {
  name: 'Items',
  props: {
    items: {
      type: Array,
      required: true,
    },
  },
  methods: {
    fullPath(path) {
      return `https://harambasic.de${path}`
    },
  },
}
</script>

<style lang="sass" scoped>
ul
  display: flex
  flex-direction: column
  flex-wrap: nowrap
  justify-content: flex-start
  align-content: space-between
  align-items: stretch
li
  > a
    display: flex
    flex-direction: row
    flex-wrap: nowrap
    justify-content: space-between
    align-content: flex-start
    align-items: center
    margin: 0 0 1rem 0
    text-decoration: none
    color: $color-primary
    transition: $animation
    border-radius: $border-radius
    padding: 1rem
    @media (prefers-color-scheme: dark)
      color: $color-light
      &:hover
        color: $color-primary
    @media screen and (max-width: $breakpoint-mobile)
      flex-direction: column
      justify-content: flex-start
      align-items: flex-start
    &:hover
      background: $color-secondary
      .icon
        background: $color-light
        svg
          fill: $color-primary
      .date
        a
          color: $color-primary
      @media (prefers-color-scheme: dark)
        .icon
          background: $color-primary
          svg
            fill: $color-secondary
    .icon
      display: flex
      flex-direction: row
      flex-wrap: nowrap
      justify-content: center
      align-content: center
      align-items: center
      background: $color-secondary
      border-radius: 50%
      font-size: 1.5rem
      line-height: 1.5rem
      padding: .5rem
      margin:  0 0 0 1rem
      transition: $animation
      @media screen and (max-width: $breakpoint-mobile)
        display: none
      svg
        fill: $color-primary
        width: 2rem
        height: 2rem
    .title
      font-size: 1.5rem
    .date
      font-size: 1rem
      @media screen and (max-width: $breakpoint-mobile)
        margin: .5rem 0 0 0
      a
        color: $color-primary
        text-decoration: none
        transition: $animation
        border-bottom: 2px solid transparent
        &:hover
          border-color: $color-primary
        @media (prefers-color-scheme: dark)
          color: $color-light
.update
  font-size: 1rem
  text-align: center
</style>

// src/components/Posts/PostsList.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { Category } from '../../types/category';
	import { SortDirection, SortProperty } from '../../types/enums';
	import type { Post } from '../../types/post';
	import { filterPostsByCategory, sortPosts } from '../../util/data/posts';
	import { getPath } from '../../util/helper';

	export let categories: Category[];
	let selectedCategory: string = 'all';

	export let posts: Post[];
	let sortedPosts: Post[] = sortPosts(posts, SortProperty.Date, SortDirection.Asc);
	$: filteredPosts = filterPostsByCategory(sortedPosts, selectedCategory);

	onMount(() => {
		selectedCategory = new URLSearchParams(window.location.search).get('category') || 'all';
	});

	function onSelectCategory(categorySlug: string) {
		selectedCategory = categorySlug;
		const url = new URL(window.location.toString());
		url.searchParams.set('category', selectedCategory);
		window.history.pushState({}, '', url.href);
	}
</script>

<section>
	<aside class="categories">
		<h2>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="16"
				height="16"
				fill="#000000"
				viewBox="0 0 256 256"
				><rect width="32" height="32" fill="none" /><path
					d="M42.1,48H213.9a8,8,0,0,1,5.9,13.4l-65.7,72.3a7.8,7.8,0,0,0-2.1,5.4v56.6a7.9,7.9,0,0,1-3.6,6.7l-32,21.3a8,8,0,0,1-12.4-6.6v-78a7.8,7.8,0,0,0-2.1-5.4L36.2,61.4A8,8,0,0,1,42.1,48Z"
					fill="none"
					stroke="#000000"
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="24"
				/></svg
			> Categories
		</h2>
		<ol>
			<li>
				<button
					class:selected={selectedCategory === 'all'}
					on:click={() => onSelectCategory('all')}
				>
					All ({posts.length})</button
				>
			</li>
			{#each categories as category}
				<li>
					<button
						class:selected={selectedCategory === category.slug}
						on:click={() => onSelectCategory(category.slug)}
					>
						{category.display} ({category.postCount})
					</button>
				</li>
			{/each}
		</ol>
	</aside>
	<div class="posts">
		<ul>
			{#each filteredPosts as post}
				<li class="h-feed">
					<a href={getPath('posts', post)}>
						<div class="column">
							<strong class="title">
								{post.title}
							</strong>
							<ul class="categories">
								{#each post.categories as category}
									<li>
										<a href={category.fullPath} class="link">
											{category.display}
										</a>
									</li>
								{/each}
							</ul>
						</div>
						<time class="date dt-published" datetime={post.publishDate.toString()}>
							{post.publishDateFormatted}
						</time>
						<svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 32 32"
							><rect width="32" height="32" fill="none" /><circle
								cx="128"
								cy="128"
								r="96"
								fill="none"
								stroke="#000000"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="24"
							/><polyline
								points="134.1 161.9 168 128 134.1 94.1"
								fill="none"
								stroke="#000000"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="24"
							/><line
								x1="88"
								y1="128"
								x2="168"
								y2="128"
								fill="none"
								stroke="#000000"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="24"
							/></svg
						>
					</a>
				</li>
			{/each}
		</ul>
	</div>
</section>

<style lang="postcss">
	h1 {
		width: 100%;
		text-align: center;
	}
	section {
		display: flex;
		flex-direction: row;
		flex-wrap: nowrap;
		align-content: stretch;
		justify-content: flex-start;
		align-items: stretch;
		gap: var(--xl);
		/* TODO align  */
		width: var(--layout-l);
		font-weight: 600;
		font-size: var(--font-m);
		font-family: var(--font-family);
		letter-spacing: var(--font-letter-spacing-headline);
	}
	.categories {
		display: flex;
		flex-direction: column;
		flex-wrap: nowrap;
		align-content: stretch;
		justify-content: flex-start;
		align-items: stretch;
		gap: var(--m);
		/* TODO align */
		width: 12rem;
		ol {
			display: flex;
			flex-direction: column;
			flex-wrap: nowrap;
			align-content: stretch;
			justify-content: flex-start;
			align-items: stretch;
			gap: var(--s);
			li {
				button {
					margin: 0;
					border: none;
					background: none;
					padding: 0;
					color: var(--c-font-80);
					font-size: var(--font-s);
					&:hover {
						cursor: pointer;
						text-decoration: underline;
						text-decoration-thickness: var(--underline-thickness);
					}
					&.selected {
						text-decoration: underline;
						text-decoration-thickness: var(--underline-thickness);
						&:hover {
							text-decoration: none;
						}
					}
				}
			}
		}
	}
	.posts {
		width: 100%;
		> ul {
			display: flex;
			flex-direction: column;
			flex-wrap: nowrap;
			align-content: stretch;
			justify-content: flex-start;
			align-items: stretch;
			gap: var(--l);
			width: 100%;
			> li {
				width: 100%;
				> a {
					display: flex;
					position: relative;
					flex-direction: row;
					flex-wrap: nowrap;
					align-content: stretch;
					justify-content: space-between;
					align-items: flex-start;
					gap: var(--l);
					transition: var(--transition);
					border-radius: var(--border-radius);
					background: var(--c-surface);
					padding: var(--l);
					color: var(--c-font);
					text-decoration: none;
					&:hover {
						transform: scale(1.05);
						cursor: pointer;
						svg {
							opacity: 1;
						}
					}
					.column {
						display: flex;
						flex-direction: column;
						flex-wrap: nowrap;
						align-content: stretch;
						justify-content: flex-start;
						align-items: stretch;
						gap: var(--xs);
					}
					.title {
						display: inline-block;
						font-weight: 900;
						font-size: var(--font-m);
						line-height: 1.2;
						font-family: var(--font-family);
						letter-spacing: var(--font-letter-spacing-headline);
					}
					.categories {
						display: flex;
						position: relative;
						flex-direction: row;
						flex-wrap: nowrap;
						align-content: stretch;
						justify-content: flex-start;
						align-items: flex-start;
						gap: var(--xs);
						li {
							a {
								color: var(--c-font-80);
								font-weight: 400;
								font-size: var(--font-s);
								text-decoration: none;
								&:hover {
									text-decoration: underline;
									text-decoration-thickness: var(--underline-thickness);
								}
							}
						}
					}
					.date {
						display: inline-block;
						margin: 0 0 var(--xs) 0;
						font-size: var(--font-m);
					}
					svg {
						size: var(--l);
						position: absolute;
						top: var(--m);
						right: calc((-1) * var(--m));
						opacity: 0;
						transition: var(--transition);
						border: 4px solid var(--c-light);
						border-radius: 100%;
						background: var(--c-light);
					}
				}
			}
		}
	}
</style>
