// components/ProjectsList.vue
<template>
  <section>
    <ul class="projects">
      <li v-for="item in items" :key="item.slug" class="project">
        <div class="meta">
          <img :src="item.img" :alt="item.alt" />
        </div>
        <div class="content">
          <h2 class="title" v-text="item.title" />
          <ul class="responsibilities">
            <li><h6>Responsibilities:</h6></li>
            <li
              v-for="responsibility in item.responsibilities"
              :key="responsibility"
              v-text="responsibility"
            />
          </ul>
          <nuxt-content class="description" :document="item" />
          <ul class="links">
            <li v-for="link in item.links" :key="link.title">
              <a class="link" :href="link.url" v-text="link.title" />
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </section>
</template>

<script>
export default {
  name: 'ProjectsList',
  props: {
    items: {
      type: Array,
      required: true,
    },
  },
}
</script>

<style lang="sass" scoped>
.projects
  display: flex
  flex-direction: column
  flex-wrap: nowrap
  justify-content: flex-start
  align-content: flex-start
  align-items: flex-start
.project
  width: 100%
  margin: 0 0 4rem 0
  background: $color-secondary
  border-radius: $border-radius
  padding: 2rem
  display: flex
  flex-wrap: nowrap
  justify-content: space-between
  align-content: stretch
  align-items: flex-start
.meta
  width: 30%
  background: $color-light
  border-radius: $border-radius
  padding: 1rem
  box-shadow: $box-shadow
  img
    border-radius: $border-radius
.content
  width: calc(70% - 2rem)
.title
  font-size: 1.75rem
.responsibilities
  opacity: .8
  font-size: .9rem
  margin: .5rem 0 1rem 0
  display: flex
  flex-direction: row
  flex-wrap: wrap
  justify-content: flex-start
  align-content: flex-start
  align-items: flex-start
  li
    margin: 0 .15rem 0 0
    &:after
      content: ', '
    &:last-of-type,
    &:first-of-type
      &:after
        content: ''
  h6
    text-transform: uppercase
.links
  margin: 1rem 0 0 0
  display: flex
  flex-direction: row
  flex-wrap: wrap
  justify-content: flex-start
  align-content: flex-start
  align-items: flex-start
  li
    margin: 0 .15rem 0 0
    &:after
      content: ', '
    &:last-of-type
      &:after
        content: ''
    a
      color: $color-primary
      border-bottom: 1px solid $color-primary
      transition: $animation
      text-decoration: none
      &:hover
        text-decoration: none
        border-color: transparent
</style>

// src/routes/projects/ProjectsList.svelte
<script lang="ts">
	import { init, entries, tags, filterTag } from '../../store/projectStore';
	import { getTagBySlug } from '../../lib/util/entries';
	import { onMount } from 'svelte';

	export let raw: any;

	onMount(() => {
		init(raw);
		const slug = new URLSearchParams(window.location.search).get('tag') || 'all';
		filterTag.set(getTagBySlug(tags.get(), slug));
	});

	function onSelectTag(slug: string) {
		filterTag.set(getTagBySlug(tags.get(), slug));
		const url = new URL(window.location.toString());
		url.searchParams.set('tag', filterTag.get().slug);
		window.history.pushState({}, '', url.href);
	}
</script>

<section>
	<!-- TODO extract -->
	<aside class="tags">
		<h2>Tags</h2>
		<ul>
			{#each $tags as tag}
				<li>
					<button
						class:selected={$filterTag.slug === tag.slug}
						on:click={() => onSelectTag(tag.slug)}
					>
						{tag.title} ({tag.count})
					</button>
				</li>
			{/each}
		</ul>
	</aside>
	<div class="entries">
		<ul>
			{#each $entries as entry}
				<li class="h-feed">
					<img src={entry.image} alt="TODO" width="8rem" />
					<div class="content">
						<strong>{entry.title}</strong>
					</div>
				</li>
			{/each}
		</ul>
	</div>
</section>

<style lang="postcss">
	section {
		display: flex;
		flex-direction: row;
		flex-wrap: nowrap;
		align-content: stretch;
		justify-content: flex-start;
		align-items: stretch;
		gap: var(--xl);
	}
	.tags {
		display: flex;
		flex-direction: column;
		flex-wrap: nowrap;
		align-content: stretch;
		justify-content: flex-start;
		align-items: stretch;
		gap: var(--m);
		width: var(--layout-sidebar);
		svg {
			fill: white;
			size: 2rem;
		}
		ul {
			display: flex;
			flex-direction: column;
			flex-wrap: nowrap;
			align-content: flex-start;
			justify-content: flex-start;
			align-items: flex-start;
			gap: var(--s);
			li {
				button {
					margin: 0;
					border: none;
					background: none;
					padding: 0;
					color: var(--c-font-accent-dark);
					font-size: var(--font-s);
					text-align: left;
					&:hover {
						cursor: pointer;
						text-decoration: underline;
						text-decoration-thickness: var(--underline-thickness);
					}
					&.selected {
						text-decoration: underline;
						text-decoration-thickness: var(--underline-thickness);
						&:hover {
							text-decoration: none;
						}
					}
				}
			}
		}
	}
	.entries {
		width: 100%;
		ul {
			display: grid;
			grid-template-columns: 1fr 1fr;
			gap: var(--xl);
			li {
				display: flex;
				position: relative;
				flex-direction: column;
				flex-wrap: nowrap;
				align-content: stretch;
				justify-content: flex-start;
				align-items: stretch;
				transition: var(--transition);
				border-radius: var(--border-radius);
				background: var(--c-surface);
				height: 100%;
				color: var(--c-font);
				text-decoration: none;
				&:hover {
					transform: scale(1.05);
					cursor: pointer;
					svg {
						opacity: 1;
					}
				}
				> img {
					border-radius: var(--border-radius) var(--border-radius) 0 0;
					aspect-ratio: 1 / 1;
					width: 100%;
				}
				> .content {
					padding: var(--l);
					strong {
						display: block;
						margin: 0 0 var(--xs) 0;
						font-weight: 900;
						font-size: var(--font-m);
						line-height: 1.2;
						font-family: var(--font-family);
						letter-spacing: var(--font-letter-spacing-headline);
					}
				}
			}
		}
	}
</style>
