// components/ListsList.vue
<template>
  <section>
    <ul>
      <li v-for="item in items" :key="item.slug" class="h-feed">
        <nuxt-link :to="item.path">
          <div>
            <h2 class="title p-name" v-text="item.title" />
            <p v-text="item.description" />
          </div>
          <!-- TODO extract in component and reuse in projectslist-->
          <div class="icon">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path d="M0 0h24v24H0V0z" fill="none" />
              <path
                d="M9.31 6.71c-.39.39-.39 1.02 0 1.41L13.19 12l-3.88 3.88c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0l4.59-4.59c.39-.39.39-1.02 0-1.41L10.72 6.7c-.38-.38-1.02-.38-1.41.01z"
              />
            </svg>
          </div>
        </nuxt-link>
      </li>
    </ul>
    <div class="update nuxt-content">
      <!-- TODO add rss feed for lists-->
      <p>
        Check out the <a href="/posts/rss.xml">RSS feed</a> or
        <a href="https://twitter.com/luka_harambasic">my Twitter account</a>
        to keep up to date.
      </p>
    </div>
  </section>
</template>

<script>
export default {
  name: 'Items',
  props: {
    items: {
      type: Array,
      required: true,
    },
  },
  methods: {
    fullPath(path) {
      return `https://harambasic.de${path}`
    },
  },
}
</script>

<style lang="sass" scoped>
ul
  display: flex
  flex-direction: column
  flex-wrap: nowrap
  justify-content: flex-start
  align-content: space-between
  align-items: stretch
li
  > a
    display: flex
    flex-direction: row
    flex-wrap: nowrap
    justify-content: space-between
    align-content: flex-start
    align-items: center
    margin: 0 0 1rem 0
    text-decoration: none
    color: $color-primary
    transition: $animation
    border-radius: $border-radius
    padding: 1rem
    @media (prefers-color-scheme: dark)
      color: $color-light
      &:hover
        color: $color-primary
    @media screen and (max-width: $breakpoint-mobile)
      flex-direction: column
      justify-content: flex-start
      align-items: flex-start
    &:hover
      background: $color-secondary
      .icon
        background: $color-light
        svg
          fill: $color-primary
      @media (prefers-color-scheme: dark)
        .icon
          background: $color-primary
          svg
            fill: $color-secondary
    .icon
      display: flex
      flex-direction: row
      flex-wrap: nowrap
      justify-content: center
      align-content: center
      align-items: center
      background: $color-secondary
      border-radius: 50%
      font-size: 1.5rem
      line-height: 1.5rem
      padding: .5rem
      margin:  0 0 0 2rem
      transition: $animation
      @media screen and (max-width: $breakpoint-mobile)
        display: none
      svg
        fill: $color-primary
        width: 2rem
        height: 2rem
    .title
      font-size: 1.5rem
.update
  margin: 1rem 0 0 0
  font-size: 1rem
  text-align: center
</style>

// src/components/Lists/ListsList.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { SortDirection, SortProperty } from '../../types/enums';
	import type { List, ListEntry } from '../../types/list';
	import { filterPostsByCategory, sortPosts } from '../../util/data/posts';
	import { getPath } from '../../util/helper';

	let selectedList: string = 'all';

	export let lists: List[];
	let sortedLists: List[] = lists; // sortLists(lists, SortProperty.Date, SortDirection.Asc);
	$: filteredListEntries = sortedLists[0].entries as ListEntry[]; // filterPostsByCategory(sortedLists, selectedList);

	onMount(() => {
		selectedList = new URLSearchParams(window.location.search).get('list') || 'all';
	});

	function onSelectList(listSLug: string) {
		selectedList = listSLug;
		const url = new URL(window.location.toString());
		url.searchParams.set('list', selectedList);
		window.history.pushState({}, '', url.href);
	}
</script>

<section>
	<aside class="lists">
		<h2>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="192"
				height="192"
				fill="#000000"
				viewBox="0 0 256 256"
				><rect width="256" height="256" fill="none" /><line
					x1="96"
					y1="156"
					x2="160"
					y2="156"
					fill="none"
					stroke="#000000"
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="24"
				/><line
					x1="96"
					y1="116"
					x2="160"
					y2="116"
					fill="none"
					stroke="#000000"
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="24"
				/><path
					d="M160,40h40a8,8,0,0,1,8,8V216a8,8,0,0,1-8,8H56a8,8,0,0,1-8-8V48a8,8,0,0,1,8-8H96"
					fill="none"
					stroke="#000000"
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="24"
				/><path
					d="M88,72V64a40,40,0,0,1,80,0v8Z"
					fill="none"
					stroke="#000000"
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="24"
				/></svg
			> Lists
		</h2>
		<ol>
			<li>
				<button class:selected={selectedList === 'all'} on:click={() => onSelectList('all')}>
					All ({lists.length})</button
				>
			</li>
			{#each sortedLists as list}
				<li>
					<button
						class:selected={selectedList === list.slug}
						on:click={() => onSelectList(list.slug)}
					>
						{list.title} ({list.entries.length})
					</button>
				</li>
			{/each}
		</ol>
	</aside>
	<div class="entries">
		<ul>
			{#each filteredListEntries as entry}
				<li class="h-feed">
					<a href={entry.url}>
						<div class="logo">
							<img src={entry.logo} alt={entry.title} width="64px" />
						</div>
						<div class="content">
							<strong class="title">
								{entry.title}
							</strong>
							<p>{entry.description}</p>
						</div>
						<svg
							xmlns="http://www.w3.org/2000/svg"
							width="192"
							height="192"
							fill="#000000"
							viewBox="0 0 256 256"
							><rect width="256" height="256" fill="none" /><polyline
								points="216 100 216 40 156 40"
								fill="none"
								stroke="#000000"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="24"
							/><line
								x1="144"
								y1="112"
								x2="216"
								y2="40"
								fill="none"
								stroke="#000000"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="24"
							/><path
								d="M184,144v64a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V80a8,8,0,0,1,8-8h64"
								fill="none"
								stroke="#000000"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="24"
							/></svg
						>
					</a>
				</li>
			{/each}
		</ul>
	</div>
</section>

<style lang="postcss">
	section {
		display: flex;
		flex-direction: row;
		flex-wrap: nowrap;
		align-content: stretch;
		justify-content: flex-start;
		align-items: stretch;
		gap: var(--xl);
		/* width: var(--layout-l); */
		font-weight: 600;
		font-size: var(--font-m);
		font-family: var(--font-family);
		letter-spacing: var(--font-letter-spacing-headline);
	}
	.lists {
		display: flex;
		flex-direction: column;
		flex-wrap: nowrap;
		align-content: stretch;
		justify-content: flex-start;
		align-items: stretch;
		gap: var(--m);
		/* TODO align */
		width: 12rem;
		svg {
			fill: white;
			size: 2rem;
		}
		ol {
			display: flex;
			flex-direction: column;
			flex-wrap: nowrap;
			align-content: stretch;
			justify-content: flex-start;
			align-items: stretch;
			gap: var(--s);
			li {
				button {
					margin: 0;
					border: none;
					background: none;
					padding: 0;
					color: var(--c-font-accent-dark);
					font-size: var(--font-s);
					&:hover {
						cursor: pointer;
						text-decoration: underline;
						text-decoration-thickness: var(--underline-thickness);
					}
					&.selected {
						text-decoration: underline;
						text-decoration-thickness: var(--underline-thickness);
						&:hover {
							text-decoration: none;
						}
					}
				}
			}
		}
	}
	.entries {
		width: 100%;
		> ul {
			display: flex;
			flex-direction: column;
			flex-wrap: nowrap;
			align-content: stretch;
			justify-content: flex-start;
			align-items: stretch;
			gap: var(--l);
			width: 100%;
			> li {
				width: 100%;
				> a {
					display: flex;
					position: relative;
					flex-direction: row;
					flex-wrap: nowrap;
					align-content: flex-start;
					justify-content: flex-start;
					align-items: stretch;
					transition: var(--transition);
					border-radius: var(--border-radius);
					background: var(--c-surface);
					overflow: hidden;
					color: var(--c-font);
					text-decoration: none;
					&:hover {
						transform: scale(1.05);
						cursor: pointer;
						svg {
							opacity: 1;
						}
					}
					.logo {
						flex-base: 16rem;
						display: flex;
						flex-shrink: 1;
						flex-direction: column;
						flex-wrap: nowrap;
						align-content: center;
						justify-content: center;
						background: var(--c-font-accent-super-light);
						padding: var(--l);
						img {
							height: 4rem;
						}
					}
					.content {
						display: flex;
						flex-direction: column;
						flex-wrap: nowrap;
						align-content: stretch;
						justify-content: flex-start;
						align-items: stretch;
						gap: var(--xs);
						padding: var(--l);
						.title {
							display: inline-block;
							font-weight: 900;
							font-size: var(--font-m);
							line-height: 1.2;
							font-family: var(--font-family);
							letter-spacing: var(--font-letter-spacing-headline);
						}
					}
					> svg {
						size: var(--l);
						position: absolute;
						top: var(--m);
						right: calc((-1) * var(--m));
						opacity: 0;
						transition: var(--transition);
						border: 4px solid var(--c-light);
						border-radius: 100%;
						background: var(--c-light);
					}
				}
			}
		}
	}
</style>
