// src/components/posts/List.svelte
<script lang="ts">
  import type { CollectionEntry } from 'astro:content'
  import Card from '@components/Card.svelte'
  import Tag from '@components/Tag.svelte'
  import Category from '@components/Category.svelte'

  let { entries, categories, tags, selectegCategoty, selectedTag } = $props<{
    entries: CollectionEntry<'posts'>[]
    categories: CollectionEntry<'categories'>[]
    tags: CollectionEntry<'tags'>[]
    selectegCategoty: string
    selectedTag: string
  }>()
</script>

<section>
  <ul class="entries">
    {#each entries as entry}
      <Card class="entry h-feed">
        <a href={`/posts/${entry.slug}`}>
          <div class="column">
            <strong class="title">{entry.data.title}</strong>
            <div class="category">Category</div>
          </div>
        </a>
      </Card>
    {/each}
  </ul>
  <aside>
    <Card direction="column">
      <h3>Categories</h3>
      <ul class="tags">
        {#each categories as category}
          <li>
            <Category {category} href={`/posts?category=${category.id}`} />
          </li>
        {/each}
      </ul>
    </Card>
    <Card direction="column">
      <h3>Tags</h3>
      <ul class="tags">
        {#each tags as tag}
          <li>
            <Tag {tag} href={`/posts?tag=${tag.id}`} />
          </li>
        {/each}
      </ul>
    </Card>
  </aside>
</section>

<style lang="postcss">
  section {
    display: grid;
    grid-template-rows: auto auto auto;
    grid-template-columns: 70ch 1fr;
    column-gap: var(--l);
    row-gap: var(--l);
    width: 100%;
    @media screen and (max-width: 74rem) {
      grid-template-columns: 1fr 18rem;
    }
    @media screen and (max-width: 50rem) {
      grid-template-columns: 1fr;
    }
    .entries {
      width: 100%;
      display: flex;
      flex-direction: column;
      flex-wrap: nowrap;
      align-content: stretch;
      justify-content: flex-start;
      align-items: stretch;
      gap: var(--l);
      @media screen and (max-width: 50rem) {
        grid-template-columns: 1fr;
        order: 1;
      }
      .entry {
        transition: var(--transition);
        &:hover {
          transform: scale(0.97);
          cursor: pointer;
          :global(svg) {
            opacity: 1;
          }
        }
        > a {
          display: flex;
          position: relative;
          flex-direction: row;
          flex-wrap: nowrap;
          align-content: stretch;
          justify-content: space-between;
          align-items: flex-start;
          gap: var(--l);
          color: var(--c-font);
          text-decoration: none;
          @media screen and (max-width: 50rem) {
            flex-direction: column-reverse;
          }
          .column {
            display: flex;
            flex-direction: column;
            flex-wrap: nowrap;
            align-content: stretch;
            justify-content: flex-start;
            align-items: stretch;
            gap: var(--xs);
          }
          .title {
            display: inline-block;
            font-weight: 900;
            font-size: var(--font-m);
            line-height: 1.2;
            font-family: var(--font-family);
            letter-spacing: var(--font-letter-spacing-headline);
          }
          .category {
            flex-base: 100%;
            display: flex;
            flex-grow: 1;
            flex-direction: row;
            flex-wrap: wrap;
            align-content: stretch;
            justify-content: flex-start;
            align-items: flex-start;
            gap: var(--xs);
            font-size: var(--font-s);
          }
          .date {
            display: inline-block;
            margin: 0 0 var(--xs) 0;
            color: var(--c-font);
            font-weight: 400;
            font-size: var(--font-m);
            text-decoration: none;
            font-style: italic;
            text-align: right;
            flex-shrink: 0;
            @media screen and (max-width: 50rem) {
              margin: 0 0 calc(-1 * var(--m)) 0;
              flex-shrink: 1;
            }
          }
          :global(.arrow) {
            color: var(--c-font-accent-dark);
            size: var(--l);
            position: absolute;
            top: var(--m);
            right: calc((-1) * var(--m));
            opacity: 0;
            transition: var(--transition);
            border: 4px solid var(--c-light);
            border-radius: 100%;
            background: var(--c-light);
            box-shadow:
              0 1px 2px rgba(0, 0, 0, 0.03),
              0 2px 4px rgba(0, 0, 0, 0.03),
              0 4px 8px rgba(0, 0, 0, 0.03),
              0 8px 16px rgba(0, 0, 0, 0.03),
              0 16px 32px rgba(0, 0, 0, 0.03),
              0 32px 64px rgba(0, 0, 0, 0.03);
          }
        }
      }
    }
    aside {
      display: flex;
      flex-direction: column;
      flex-wrap: nowrap;
      align-content: stretch;
      justify-content: flex-start;
      align-items: stretch;
      gap: var(--l);
      width: 100%;
      @media screen and (max-width: 50rem) {
        grid-template-columns: 1fr;
        order: 0;
      }
      .tags {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        gap: var(--xs);
        align-items: flex-start;
        justify-content: flex-start;
      }
    }
  }
</style>

// components/List.vue
<template>
  <article class="post h-entry">
    <header>
      <h1 class="p-name" v-text="item.title" />
      <p v-text="item.description" />
    </header>
    <section>
      <ul>
        <li v-for="entry in item.list" :key="entry.title">
          <a :href="entry.url">
            <img class="logo" :src="entry.logo" :alt="entry.title" />
            <div class="content">
              <strong class="title" v-text="entry.title" />
              <p class="description" v-text="entry.description" />
            </div>
          </a>
        </li>
      </ul>
    </section>
  </article>
</template>

<script>
export default {
  name: 'Item',
  props: {
    item: {
      type: Object,
      required: true,
    },
  },
}
</script>

<style lang="sass" scoped>
header
  margin: 0 0 2rem 0
  > h1
    font-size: 1.75rem
    line-height: 1.5
    margin: 0 0 1rem 0
  > p
li
  > a
    display: flex
    flex-direction: row
    flex-wrap: nowrap
    justify-content: flex-start
    align-content: stretch
    align-items: center
    margin: 0 0 1rem 0
    text-decoration: none
    color: $color-primary
    transition: $animation
    border-radius: $border-radius
    padding: 1rem
    @media (prefers-color-scheme: dark)
      color: $color-light
      &:hover
        color: $color-primary
    @media screen and (max-width: $breakpoint-mobile)
      flex-direction: column
      justify-content: flex-start
      align-items: flex-start
    &:hover
      background: $color-secondary
    .logo
      width: 5rem
      height: 5rem
      margin: 0 2rem 0 0
    .title
      font-size: 1.5rem
      font-weight: bold
</style>
