// src/routes/posts/Post.svelte
<script lang="ts">
	import BaseCallout from '$lib/components/Base/BaseCallout.svelte';
	import PostsTableOfContent from './TableOfContent.svelte';
	import type { Post } from '$lib/types/post';

	export let post: Post;
	const {
		title,
		published,
		updated,
		tldr,
		tags,
		description,
		image,
		slug,
		relativePath,
		fullPath,
		toc,
		html
	} = post;
</script>

<article class="post h-entry">
	<!-- TODO the 4 section could be split up in dedicated files -->
	<div class="meta">
		<time class="date dt-published" datetime={published.raw.toString()}>
			<a href={relativePath} class="u-url">{published.display}</a>
		</time>
		<div class="tags">
			<ul>
				{#each tags as tag}
					<li>
						<a href={tag.fullPath} class="link">
							{tag.display}
						</a>
					</li>
				{/each}
			</ul>
		</div>
		<div class="read-time">3min</div>
		<div class="discussion">Discuss on Mastodon</div>
	</div>
	<div class="toc">
		<div class="content">
			<PostsTableOfContent nodes={toc} />
		</div>
	</div>
	<div class="tldr">
		<BaseCallout prefix="TL;DR">
			{@html tldr}
		</BaseCallout>
	</div>
	<section class="post">
		<div class="content rich-text e-content">
			{@html html}
		</div>
	</section>
	<footer class="rich-text">
		<div class="follow">
			<!-- TODO links -->
			If you have any thoughts or questions feel free to share them in
			<a href="post.tweet">this thread</a> or send me an
			<a href="globals.mailto">email</a>. And if you want to stay up to date you can subscribe to
			the <a href="globals.blogFeedURL">RSS feed</a>.
		</div>
		<div class="author">
			<a href="https://harambasic.de" rel="author" class="p-author h-card">by Luka Harambasic</a>
		</div>
	</footer>
</article>

<style>
	article {
		display: grid;
		grid-template-rows: auto 1fr auto;
		grid-template-columns: 70ch 1fr;
		grid-template-areas: 'tldr meta' 'post toc' 'footer footer';
		column-gap: var(--l);
		row-gap: var(--l);
		.meta {
			display: flex;
			grid-area: meta;
			flex-direction: column;
			flex-wrap: nowrap;
			align-content: stretch;
			justify-content: flex-start;
			align-items: stretch;
			gap: var(--m);
			border-radius: var(--border-radius);
			background: var(--c-surface);
			padding: var(--l);
			.date {
				a {
					color: var(--c-font-680);
					font-weight: 400;
					font-size: var(--font-s);
				}
			}
			.tags {
				ul {
					display: flex;
					position: relative;
					flex-direction: row;
					flex-wrap: wrap;
					align-content: stretch;
					justify-content: flex-start;
					align-items: flex-start;
					gap: var(--xs);
					li {
						a {
							color: var(--c-font-accent-dark);
							font-weight: 400;
							font-size: var(--font-s);
							&:hover {
								text-decoration: none;
							}
						}
					}
				}
			}
		}
		.toc {
			grid-area: toc;
			.content {
				position: sticky;
				top: var(--l);
				border-radius: var(--border-radius);
				background: var(--c-surface);
				padding: var(--l);
				strong {
					display: block;
					margin: 0 0 var(--m) 0;
					font-weight: 900;
					font-size: var(--font-l);
					font-family: var(--font-family);
					letter-spacing: var(--font-letter-spacing-headline);
				}
			}
		}
		.tldr {
			grid-area: tldr;
		}
		.post {
			grid-area: post;
		}
		footer {
			grid-area: footer;
			border-radius: var(--border-radius);
			background: var(--c-surface);
			padding: var(--l);
			.author {
				text-align: center;
				a {
					font-weight: 900;
					font-size: var(--font-s);
					line-height: 1.2;
					font-family: var(--font-family);
					letter-spacing: var(--font-letter-spacing-headline);
					text-decoration: none;
					&:hover {
						text-decoration: underline;
						text-decoration-thickness: var(--underline-thickness);
					}
				}
			}
		}
	}
</style>

// components/Post.vue
<template>
  <article class="post h-entry">
    <section>
      <img class="image" :src="item.image" :alt="item.alt" />
      <div class="row-space-between">
        <h1 class="title p-name" v-text="item.title" />
        <time class="date dt-published" :datetime="item.createdAt">
          <a :href="fullPath" class="u-url">{{ item.createdAt | date }}</a>
        </time>
      </div>
      <meta-list class="tags" :items="item.tags" pre-text="Tags:" />
      <callout class="tldr p-summary">
        <strong slot="sprefix">TL;DR</strong>
        {{ item.tldr }}
      </callout>
      <nuxt-content class="content e-content" :document="item" />
    </section>
    <section>
      <callout class="follow">
        Do you have thoughts on this topic? Share them in
        <a :href="item.tweet">this thread</a>. <br />
        You can subscribe to this blog via <a href="/posts/rss.xml">RSS</a> or
        follow me on
        <a href="https://twitter.com/luka_harambasic">Twitter</a> to get the
        latest updates.
        <br />
        And if you find typos fell free to open a
        <a href="https://github.com/LukaHarambasic/harambasic.de/pulls">PR</a>
        (for <a :href="gitHubURL">this file</a>).
      </callout>
      <div class="author">
        <a href="https://harambasic.de" rel="author" class="p-author h-card"
          >by Luka Harambasic</a
        >
      </div>
    </section>
  </article>
</template>

<script>
import MetaList from '@/components/MetaList'
export default {
  name: 'Item',
  components: { MetaList },
  props: {
    item: {
      type: Object,
      required: true,
    },
  },
  computed: {
    fullPath() {
      return `https://harambasic.de${this.item.path}`
    },
    gitHubURL() {
      return `https://github.com/LukaHarambasic/harambasic.de/blob/main/content/posts/${this.item.slug}.md`
    },
  },
}
</script>

<style lang="sass" scoped>
.post
  display: flex
  flex-direction: column
  flex-wrap: nowrap
  justify-content: flex-start
  align-content: stretch
  align-items: stretch
  @media screen and (max-width: $breakpoint-desktop)
    flex-direction: column
.image
  margin: 0 0 2rem 0
  background: $color-secondary
  padding: 1rem
  border-radius: $border-radius
  width: 100%
  min-height: 16rem
  @media screen and (max-width: $breakpoint-desktop)
    min-height: 12rem
  @media screen and (max-width: $breakpoint-mobile)
    min-height: 8rem
.title
  font-size: 1.75rem
  line-height: 1.1
  margin: 0 0 .5rem 0
.date
  background: $color-secondary
  padding: .25rem .5rem
  border-radius: $border-radius
  font-size: .9rem
  @media screen and (max-width: $breakpoint-mobile)
    margin: 0 0 .25rem .25rem
  a
    color: $color-primary
    text-decoration: none
    transition: $animation
    border-bottom: 2px solid transparent
    &:hover
      border-color: $color-primary
.tags
  margin: 1rem 0 2rem 0
.author
  width: 100%
  text-align: center
  a
    color: $color-primary
    font-size: .9rem
    text-decoration: none
    transition: $animation
    border-bottom: 2px solid transparent
    &:hover
      border-color: $color-primary
    @media (prefers-color-scheme: dark)
      color: $color-light
      &:hover
        border-color: $color-light
</style>
